Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-03, with the labels that each got.

#57 Move (and fix) deployment of test website
  .github/workflows/deploy_to_github_io.yml
  .github/workflows/test-and-build.yml
Labels: bumpless

#58 Moar dev deploy fixes
  .github/workflows/deploy_to_github_io.yml
Labels: CI/CD, bumpless

#64 Pull in latest theme and setup dev site url correctly
  .github/workflows/deploy_to_github_io.yml
  environment.yml
Labels: CI/CD, bumpless

#65 fix typo in hyp3_sdk, asf_tools version update workflows
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
Labels: bumpless

#66 Add redirect for removed RTC product guide PDF
  mkdocs.yml
Labels: bumpless

#67 Actually handle redirect of RTC product guide PDF
  docs/guides/Sentinel_RTC_Product_Guide.pdf/index.html
  mkdocs.yml
Labels: bumpless

#71 Remove targets in README and fix some minor typos
  README.md
  docs/guides/rtc_product_guide.md
Labels: bumpless

#68 Release: initial md product guide, sdk 1.0 autodoc, theme update
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy_to_github_io.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test-and-build.yml
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
  .gitignore
  .gitleaks.toml
  .trufflehog.txt
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  docs/README.md
  docs/contributing.md
  docs/guides/Sentinel_RTC_Product_Guide.pdf
  docs/guides/Sentinel_RTC_Product_Guide.pdf/index.html
  docs/guides/rtc_product_guide.md
  docs/images/landsat-false-color-composite.jpg
  docs/images/log-difference-raster.png
  docs/images/sar-optical-fusion.jpg
  docs/images/seasonal-change-example.jpg
  docs/images/sentinel-1-rtc-image.jpg
  docs/images/water-histogram.png
  docs/images/water-mask.png
  docs/index.md
  docs/using/sdk.md
  environment.yml
Labels: minor
