Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-08, with the labels that each got.

#144 Release v0.3.9
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: patch

#139 Water mask option
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation, patch

#156 Change water masking announcement to be sdk-specific
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation

#157 Release 0.3.14
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: patch
