Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-07, with the labels that each got.

#133 Provide version on API reference page for SDK and API
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
  .gitignore
  docs/tools/asf_tools_api.md
  docs/using/sdk_api.md
Labels: bumpless

#135 HyP3 SDK v1.2.0 📢 Tweet
  tweets/hyp3-sdk-v1.2.0.tweet
Labels: bumpless

#136 Release what's new page and twitter integration
  .github/CODEOWNERS
  .github/workflows/propose-tweet.yml
  .github/workflows/release.yml
  .github/workflows/twitter-together.yml
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
  .gitignore
  CHANGELOG.md
  docs/index.md
  docs/tools/asf_tools_api.md
  docs/using/sdk_api.md
  docs/whats_new.md
  mkdocs.yml
  tweets/README.md
  tweets/hyp3-sdk-v1.2.0.tweet
Labels: patch

#137 fix typo in release workflow
  .github/workflows/release.yml
Labels: bumpless

#138 Water mask documentation
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation, patch

#140 Create hyp3-v2.0.2.tweet
  tweets/hyp3-v2.0.2.tweet
Labels: bumpless

#142 Release v0.3.8
  .github/workflows/release.yml
  CHANGELOG.md
  docs/guides/insar_product_guide.md
  tweets/hyp3-v2.0.2.tweet
Labels: patch

#141 Update InSAR Product Guide to include ellipsoid incidence angle map
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation, patch

#143 Update water mask description in InSAR PG to include large inland waterbodies
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: bumpless, documentation
