Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-05, with the labels that each got.

#93 A collection of InSAR updates
  docs/guides/insar_product_guide.md
Labels: bumpless

#94 Clarify that we do not offer atmospheric correction options
  docs/guides/insar_product_guide.md
Labels: bumpless, documentation

#95 Remove equation and figures for DEM processing applications
  docs/guides/insar_product_guide.md
Labels: bumpless, documentation

#96 Additional edits
  docs/guides/insar_product_guide.md
  docs/images/baseline2.png
  docs/images/phi_topo_eq.png
Labels: bumpless, documentation

#104 remove headers for unfinished sections from Introduction to SAR
  docs/guides/introduction_to_sar.md
Labels: bumpless

#105 drop unused plugin placeholders
  docs/plugins/autoRIFT.md
  docs/plugins/gamma.md
Labels: bumpless

#103 Add links for the story maps to the Products page
  docs/products.md
Labels: bumpless, documentation

#111 Update autoRIFT anchor in link on DEM page
  docs/dems.md
Labels: bumpless

#113 Replace phase_diff png file with typo-corrected png
  docs/images/phase_diff.png
Labels: bumpless, documentation

#112 Release InSAR product guide
  .github/workflows/static-analysis.yml
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
  CHANGELOG.md
  docs/contact-snippet.md
  docs/contact.md
  docs/dems.md
  docs/guides/insar_product_guide.md
  docs/guides/introduction_to_sar.md
  docs/guides/rtc_product_guide.md
  docs/images/SAR_band_types.png
  docs/images/asf_insar_names.png
  docs/images/baseline.png
  docs/images/microwave-emr.png
  docs/images/orbit_in_name.png
  docs/images/phase_diff.png
  docs/images/polarizations.png
  docs/images/scattering_types.png
  docs/images/wavelength_vs_roughness.png
  docs/index.md
  docs/plugins/autoRIFT.md
  docs/plugins/gamma.md
  docs/products.md
  docs/usage_guidelines.md
  docs/using/api.md
  mkdocs.yml
Labels: minor

#118 HOTFIX: InSAR API example job type
  CHANGELOG.md
  docs/using/api.md
Labels: bug, patch

#119 Insar options update
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation

#120 Update InSAR Processing Options
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation, patch
