Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-06, with the labels that each got.

#121 DOI badge on README
  README.md
Labels: bumpless

#123 Adding descriptions of the InSAR parameters
  docs/guides/insar_product_guide.md
Labels: bumpless

#124 fix typo and word wrapping for insar parameter file
  docs/guides/insar_product_guide.md
Labels: bumpless

#125 Update metadata tables in InSAR and RTC Product Guides
  docs/guides/insar_product_guide.md
  docs/guides/rtc_product_guide.md
Labels: bumpless

#126 Release 0.3.5
  CHANGELOG.md
  README.md
  docs/guides/insar_product_guide.md
  docs/guides/rtc_product_guide.md
Labels: patch

#128 Update release.yml
  .github/workflows/release.yml
Labels: CI/CD, bumpless
