Repository ASFHyP3/hyp3-docs, pull requests merged in 2021-04, with the labels that each got.

#73 add documentation for job truncation
  docs/using/api.md
Labels: bumpless

#76 remove 'sdk/api only' labels for insar/autorift on products page
  docs/products.md
Labels: bumpless

#69 Dem changes
  CHANGELOG.md
  docs/dems.md
  docs/guides/rtc_product_guide.md
  docs/images/cop-coverage-map.png
  docs/images/cop-missing-100.png
  docs/images/sar_distortions.png
Labels: documentation

#78 Remove gitsnippet in favor of macros
  docs/tools/arcgis_toolbox.md
  docs/tools/asf_tools.md
  docs/using/sdk.md
  environment.yml
  macros.py
  mkdocs.yml
Labels: bumpless

#77 add introductory text to the RTC Product Guide
  CHANGELOG.md
  docs/guides/rtc_product_guide.md
  environment.yml
Labels: documentation

#81 Release RTC product guide updates
  .github/workflows/tag-release.yml
  .github/workflows/test-build.yml
  CHANGELOG.md
  docs/dems.md
  docs/guides/rtc_product_guide.md
  docs/images/cop-coverage-map.png
  docs/images/cop-missing-100.png
  docs/images/sar_distortions.png
  docs/products.md
  docs/tools/arcgis_toolbox.md
  docs/tools/asf_tools.md
  docs/using/api.md
  docs/using/sdk.md
  environment.yml
  macros.py
  mkdocs.yml
Labels: minor

#89 fix branch name typo in sdk/asf_tools workflows
  .github/workflows/update_asf_tools_version.yml
  .github/workflows/update_sdk_version.yml
Labels: bumpless

#91 Fix trufflehog last tag export
  .github/workflows/static-analysis.yml
Labels: bumpless
