Repository ASFHyP3/hyp3-docs, pull requests merged in 2022-06, with the labels that each got.

#221 Update coverage map for Copernicus GLO-30 DEM
  CHANGELOG.md
  docs/images/cop-coverage-map.png
  environment.yml
Labels: documentation, patch

#224 Add Tom's ORCID
  CITATION.cff
Labels: bumpless

#233 Release 0.3.40 -- Tutorials landing page
  CHANGELOG.md
  docs/tutorials.md
  docs/using/vertex.md
  mkdocs.yml
Labels: patch
