Repository ASFHyP3/hyp3-docs, pull requests merged in 2023-12, with the labels that each got.

#397 remove the legacy option
  CHANGELOG.md
  docs/dems.md
  docs/guides/rtc_product_guide.md
Labels: patch

#398 release v 0.8.2
  CHANGELOG.md
  docs/dems.md
  docs/guides/rtc_product_guide.md
Labels: patch

#400 Edits to DEM documentation
  docs/dems.md
  docs/guides/rtc_product_guide.md
Labels: documentation, bumpless

#401 Release V 0.8.2
  docs/dems.md
  docs/guides/rtc_product_guide.md
Labels: bumpless
