Repository ASFHyP3/hyp3-docs, pull requests merged in 2023-11, with the labels that each got.

#386 Update InSAR Product Guide with Vertex ADF parameter announcement
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: documentation

#387 Release v0.6.6
  CHANGELOG.md
  docs/guides/insar_product_guide.md
Labels: patch

#390 Release v0.7.0
  .github/dictionary.txt
  CHANGELOG.md
  docs/guides/burst_insar_product_guide.md
  docs/guides/insar_product_guide.md
  docs/guides/insar_product_guide_template.md
  mkdocs.yml
Labels: minor

#391 Announcement for Burst InSAR in Vertex
  CHANGELOG.md
  docs/guides/burst_insar_product_guide.md
Labels: patch

#392 Release 0.7.1 - Burst InSAR in Vertex
  CHANGELOG.md
  docs/guides/burst_insar_product_guide.md
Labels: patch
