Repository ASFHyP3/hyp3-docs, pull requests merged in 2024-06, with the labels that each got.

#451 Proposed edits to requesting access page
  docs/using/requesting_access.md
Labels: documentation

#452 Release v0.9.3
  .github/workflows/check-links.yml
  CHANGELOG.md
  docs/using/requesting_access.md
  mkdocs.yml
  overrides/main.html
Labels: patch

#454 Release v0.9.4
  CHANGELOG.md
  docs/using/requesting_access.md
  mkdocs.yml
  overrides/main.html
Labels: patch

#457 Document announcement banner
  .github/dictionary.txt
  README.md
  overrides/main.html
Labels: bumpless
