Repository ASFHyP3/hyp3-docs, pull requests merged in 2025-03, with the labels that each got.

#522 Proposed edits to ARIA GUNW Product Guide
  docs/guides/gunw_product_guide.md
  docs/using/api.md
Labels: documentation, bumpless

#525 Update reference link
  docs/guides/gunw_product_guide.md
  docs/images/slc_jitter.png
Labels: documentation, bumpless

#527 Updates to ARIA GUNW Product Guide
  .github/dictionary.txt
  docs/guides/gunw_product_guide.md
Labels: documentation, bumpless

#529 revert adding gunw-specific blocks to insar product guide template
  docs/guides/insar_product_guide_template.md
Labels: bumpless

#530 Update aria gunw filename image
  docs/images/asf_gunw_names.png
Labels: bumpless

#531 add ARIA S1 GUNW entry to credit cost page
  docs/using/credits.md
Labels: bumpless

#532 update gunw naming convention text
  docs/guides/gunw_product_guide.md
Labels: bumpless

#533 Update job name in gunw api example; update broken s1 naming convetion links
  docs/using/api.md
Labels: bumpless

#528 Release v0.9.16
  .github/dictionary.txt
  .github/workflows/changelog.yml
  .github/workflows/check-links.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-release.yml
  CHANGELOG.md
  docs/guides/gunw_product_guide.md
  docs/guides/insar_product_guide_template.md
  docs/images/asf_gunw_names.png
  docs/images/frame_granule_overlap.png
  docs/images/slc_jitter.png
  docs/images/vertex-GUNW-dataset-selection.png
  docs/using/api.md
  docs/using/credits.md
  mkdocs.yml
  requirements.txt
Labels: patch

#539 Specify pixel spacing for ARIA GUNW and AutoRIFT products
  docs/using/credits.md
Labels: bumpless

#540 Release v0.10.0
  CHANGELOG.md
  docs/using/credits.md
  docs/using/vertex.md
  macros.py
Labels: minor

#542 Update Products landing page to include all InSAR job types
  CHANGELOG.md
  docs/products.md
Labels: documentation, patch

#546 Release v0.10.2
  CHANGELOG.md
  docs/products.md
  docs/using/api.md
Labels: patch

#541 Proposed edits to Burst InSAR product guide
  .github/dictionary.txt
  CHANGELOG.md
  docs/dems.md
  docs/guides/burst_insar_product_guide.md
  docs/guides/insar_product_guide.md
  docs/guides/rtc_product_guide.md
  docs/images/burst-contiguity.png
  docs/products.md
  docs/using/api.md
  docs/using/sdk.md
  docs/using/sdk_api.md
  environment.yml
Labels: documentation

#548 Additional edits for multi-burst docs
  docs/guides/burst_insar_product_guide.md
  docs/guides/insar_product_guide_template.md
Labels: documentation

#536 Add multiburst documentation
  .github/dictionary.txt
  CHANGELOG.md
  docs/dems.md
  docs/guides/burst_insar_product_guide.md
  docs/guides/insar_product_guide.md
  docs/guides/insar_product_guide_template.md
  docs/guides/rtc_product_guide.md
  docs/images/burst-contiguity.png
  docs/using/api.md
Labels: documentation, patch

#549 Release v0.10.3
  .github/dictionary.txt
  CHANGELOG.md
  docs/dems.md
  docs/guides/burst_insar_product_guide.md
  docs/guides/insar_product_guide.md
  docs/guides/insar_product_guide_template.md
  docs/guides/rtc_product_guide.md
  docs/images/burst-contiguity.png
  docs/using/api.md
Labels: patch
